### PR TITLE
add more metrics

### PR DESCRIPTION
**Pull request by tmatias**
Recommended by https://www.datadoghq.com/blog/sql-server-monitoring/

  The other ones are either already exported or not as pratical
  to export (such as the per-table or per-index ones).

Btw, thanks for the project!

### CODE REVIEW

**Comment by tmatias** [comment]
A sample with with I'm adding:

```
# HELP up UP Status
# TYPE up gauge
up 1

# HELP mssql_instance_local_time Number of seconds since epoch on local instance
# TYPE mssql_instance_local_time gauge
mssql_instance_local_time 1531331946

# HELP mssql_connections Number of active connections
# TYPE mssql_connections gauge
mssql_connections{database="master",state="current"} 57
mssql_connections{database="msdb",state="current"} 3

# HELP mssql_deadlocks Number of lock requests per second that resulted in a deadlock since last restart
# TYPE mssql_deadlocks gauge
mssql_deadlocks 0

# HELP mssql_user_errors Number of user errors/sec since last restart
# TYPE mssql_user_errors gauge
mssql_user_errors 183

# HELP mssql_sql_compilations Number of SQL compilations per second. Indicates the number of times the compile code path is entered. Includes compiles caused by statement-level recompilations in SQL Server. After SQL Server user activity is stable, this value reaches a steady state
# TYPE mssql_sql_compilations gauge
mssql_sql_compilations 29586

# HELP mssql_sql_recompilations Number of statement recompiles per second. Counts the number of times statement recompiles are triggered. Generally, you want the recompiles to be low
# TYPE mssql_sql_recompilations gauge
mssql_sql_recompilations 283

# HELP mssql_buffer_cache_hit_ratio Indicates the percentage of pages found in the buffer cache without having to read from disk. The ratio is the total number of cache hits divided by the total number of cache lookups over the last few thousand page accesses. After a long period of time, the ratio moves very little
# TYPE mssql_buffer_cache_hit_ratio gauge
mssql_buffer_cache_hit_ratio 4

# HELP mssql_checkpoint_pages Indicates the number of pages flushed to disk per second by a checkpoint or other operation that require all dirty pages to be flushed
# TYPE mssql_checkpoint_pages gauge
mssql_checkpoint_pages 1064

# HELP mssql_lock_waits Number of lock requests per second that required the caller to wait
# TYPE mssql_lock_waits gauge
mssql_lock_waits 21

# HELP mssql_page_splits Number of page splits per second that occur as the result of overflowing index pages
# TYPE mssql_page_splits gauge
mssql_page_splits 1148

# HELP mssql_kill_connection_errors Number of kill connection errors/sec since last restart
# TYPE mssql_kill_connection_errors gauge
mssql_kill_connection_errors 0

# HELP mssql_log_growths Total number of times the transaction log for the database has been expanded last restart
# TYPE mssql_log_growths gauge
mssql_log_growths{database="contabil_log"} 0
mssql_log_growths{database="contabil"} 0
mssql_log_growths{database="tempdb"} 0
mssql_log_growths{database="model"} 0
mssql_log_growths{database="rdsadmin"} 1
mssql_log_growths{database="msdb"} 0
mssql_log_growths{database="mssqlsystemresource"} 0
mssql_log_growths{database="master"} 0

# HELP mssql_page_life_expectancy Indicates the minimum number of seconds a page will stay in the buffer pool on this node without references. The traditional advice from Microsoft used to be that the PLE should remain above 300 seconds
# TYPE mssql_page_life_expectancy gauge
mssql_page_life_expectancy 178103

# HELP mssql_io_stall Wait time (ms) of stall since last restart
# TYPE mssql_io_stall gauge
mssql_io_stall{database="master",type="read"} 383
mssql_io_stall{database="master",type="write"} 3715
mssql_io_stall{database="master",type="queued_read"} 0
mssql_io_stall{database="master",type="queued_write"} 0
mssql_io_stall{database="tempdb",type="read"} 62
mssql_io_stall{database="tempdb",type="write"} 143
mssql_io_stall{database="tempdb",type="queued_read"} 0
mssql_io_stall{database="tempdb",type="queued_write"} 0
mssql_io_stall{database="model",type="read"} 406
mssql_io_stall{database="model",type="write"} 2585
mssql_io_stall{database="model",type="queued_read"} 0
mssql_io_stall{database="model",type="queued_write"} 0
mssql_io_stall{database="msdb",type="read"} 1451
mssql_io_stall{database="msdb",type="write"} 6582
mssql_io_stall{database="msdb",type="queued_read"} 0
mssql_io_stall{database="msdb",type="queued_write"} 0
mssql_io_stall{database="rdsadmin",type="read"} 1163
mssql_io_stall{database="rdsadmin",type="write"} 26542
mssql_io_stall{database="rdsadmin",type="queued_read"} 0
mssql_io_stall{database="rdsadmin",type="queued_write"} 0
mssql_io_stall{database="contabil",type="read"} 2287
mssql_io_stall{database="contabil",type="write"} 2866
mssql_io_stall{database="contabil",type="queued_read"} 0
mssql_io_stall{database="contabil",type="queued_write"} 0
mssql_io_stall{database="contabil_log",type="read"} 479
mssql_io_stall{database="contabil_log",type="write"} 2163
mssql_io_stall{database="contabil_log",type="queued_read"} 0
mssql_io_stall{database="contabil_log",type="queued_write"} 0

# HELP mssql_io_stall_total Wait time (ms) of stall since last restart
# TYPE mssql_io_stall_total gauge
mssql_io_stall_total{database="master"} 3720
mssql_io_stall_total{database="tempdb"} 148
mssql_io_stall_total{database="model"} 2991
mssql_io_stall_total{database="msdb"} 7260
mssql_io_stall_total{database="rdsadmin"} 27705
mssql_io_stall_total{database="contabil"} 3243
mssql_io_stall_total{database="contabil_log"} 2434

# HELP mssql_batch_requests Number of Transact-SQL command batches received per second. This statistic is affected by all constraints (such as I/O, number of users, cachesize, complexity of requests, and so on). High batch requests mean good throughput
# TYPE mssql_batch_requests gauge
mssql_batch_requests 144190

# HELP mssql_page_fault_count Number of page faults since last restart
# TYPE mssql_page_fault_count gauge
mssql_page_fault_count 1429899

# HELP mssql_memory_utilization_percentage Percentage of memory utilization
# TYPE mssql_memory_utilization_percentage gauge
mssql_memory_utilization_percentage 100

# HELP mssql_total_physical_memory_kb Total physical memory in KB
# TYPE mssql_total_physical_memory_kb gauge
mssql_total_physical_memory_kb 2096752

# HELP mssql_available_physical_memory_kb Available physical memory in KB
# TYPE mssql_available_physical_memory_kb gauge
mssql_available_physical_memory_kb 363284

# HELP mssql_total_page_file_kb Total page file in KB
# TYPE mssql_total_page_file_kb gauge
mssql_total_page_file_kb 2621040

# HELP mssql_available_page_file_kb Available page file in KB
# TYPE mssql_available_page_file_kb gauge
mssql_available_page_file_kb 620376
```

**Comment by tmatias** [comment]
A sample with the metrics I'm adding:

```
# HELP up UP Status
# TYPE up gauge
up 1

# HELP mssql_instance_local_time Number of seconds since epoch on local instance
# TYPE mssql_instance_local_time gauge
mssql_instance_local_time 1531331946

# HELP mssql_connections Number of active connections
# TYPE mssql_connections gauge
mssql_connections{database="master",state="current"} 57
mssql_connections{database="msdb",state="current"} 3

# HELP mssql_deadlocks Number of lock requests per second that resulted in a deadlock since last restart
# TYPE mssql_deadlocks gauge
mssql_deadlocks 0

# HELP mssql_user_errors Number of user errors/sec since last restart
# TYPE mssql_user_errors gauge
mssql_user_errors 183

# HELP mssql_sql_compilations Number of SQL compilations per second. Indicates the number of times the compile code path is entered. Includes compiles caused by statement-level recompilations in SQL Server. After SQL Server user activity is stable, this value reaches a steady state
# TYPE mssql_sql_compilations gauge
mssql_sql_compilations 29586

# HELP mssql_sql_recompilations Number of statement recompiles per second. Counts the number of times statement recompiles are triggered. Generally, you want the recompiles to be low
# TYPE mssql_sql_recompilations gauge
mssql_sql_recompilations 283

# HELP mssql_buffer_cache_hit_ratio Indicates the percentage of pages found in the buffer cache without having to read from disk. The ratio is the total number of cache hits divided by the total number of cache lookups over the last few thousand page accesses. After a long period of time, the ratio moves very little
# TYPE mssql_buffer_cache_hit_ratio gauge
mssql_buffer_cache_hit_ratio 4

# HELP mssql_checkpoint_pages Indicates the number of pages flushed to disk per second by a checkpoint or other operation that require all dirty pages to be flushed
# TYPE mssql_checkpoint_pages gauge
mssql_checkpoint_pages 1064

# HELP mssql_lock_waits Number of lock requests per second that required the caller to wait
# TYPE mssql_lock_waits gauge
mssql_lock_waits 21

# HELP mssql_page_splits Number of page splits per second that occur as the result of overflowing index pages
# TYPE mssql_page_splits gauge
mssql_page_splits 1148

# HELP mssql_kill_connection_errors Number of kill connection errors/sec since last restart
# TYPE mssql_kill_connection_errors gauge
mssql_kill_connection_errors 0

# HELP mssql_log_growths Total number of times the transaction log for the database has been expanded last restart
# TYPE mssql_log_growths gauge
mssql_log_growths{database="app_log"} 0
mssql_log_growths{database="app"} 0
mssql_log_growths{database="tempdb"} 0
mssql_log_growths{database="model"} 0
mssql_log_growths{database="rdsadmin"} 1
mssql_log_growths{database="msdb"} 0
mssql_log_growths{database="mssqlsystemresource"} 0
mssql_log_growths{database="master"} 0

# HELP mssql_page_life_expectancy Indicates the minimum number of seconds a page will stay in the buffer pool on this node without references. The traditional advice from Microsoft used to be that the PLE should remain above 300 seconds
# TYPE mssql_page_life_expectancy gauge
mssql_page_life_expectancy 178103

# HELP mssql_io_stall Wait time (ms) of stall since last restart
# TYPE mssql_io_stall gauge
mssql_io_stall{database="master",type="read"} 383
mssql_io_stall{database="master",type="write"} 3715
mssql_io_stall{database="master",type="queued_read"} 0
mssql_io_stall{database="master",type="queued_write"} 0
mssql_io_stall{database="tempdb",type="read"} 62
mssql_io_stall{database="tempdb",type="write"} 143
mssql_io_stall{database="tempdb",type="queued_read"} 0
mssql_io_stall{database="tempdb",type="queued_write"} 0
mssql_io_stall{database="model",type="read"} 406
mssql_io_stall{database="model",type="write"} 2585
mssql_io_stall{database="model",type="queued_read"} 0
mssql_io_stall{database="model",type="queued_write"} 0
mssql_io_stall{database="msdb",type="read"} 1451
mssql_io_stall{database="msdb",type="write"} 6582
mssql_io_stall{database="msdb",type="queued_read"} 0
mssql_io_stall{database="msdb",type="queued_write"} 0
mssql_io_stall{database="rdsadmin",type="read"} 1163
mssql_io_stall{database="rdsadmin",type="write"} 26542
mssql_io_stall{database="rdsadmin",type="queued_read"} 0
mssql_io_stall{database="rdsadmin",type="queued_write"} 0
mssql_io_stall{database="app",type="read"} 2287
mssql_io_stall{database="app",type="write"} 2866
mssql_io_stall{database="app",type="queued_read"} 0
mssql_io_stall{database="app",type="queued_write"} 0
mssql_io_stall{database="app",type="read"} 479
mssql_io_stall{database="app",type="write"} 2163
mssql_io_stall{database="app_log",type="queued_read"} 0
mssql_io_stall{database="app_log",type="queued_write"} 0

# HELP mssql_io_stall_total Wait time (ms) of stall since last restart
# TYPE mssql_io_stall_total gauge
mssql_io_stall_total{database="master"} 3720
mssql_io_stall_total{database="tempdb"} 148
mssql_io_stall_total{database="model"} 2991
mssql_io_stall_total{database="msdb"} 7260
mssql_io_stall_total{database="rdsadmin"} 27705
mssql_io_stall_total{database="app"} 3243
mssql_io_stall_total{database="app_log"} 2434

# HELP mssql_batch_requests Number of Transact-SQL command batches received per second. This statistic is affected by all constraints (such as I/O, number of users, cachesize, complexity of requests, and so on). High batch requests mean good throughput
# TYPE mssql_batch_requests gauge
mssql_batch_requests 144190

# HELP mssql_page_fault_count Number of page faults since last restart
# TYPE mssql_page_fault_count gauge
mssql_page_fault_count 1429899

# HELP mssql_memory_utilization_percentage Percentage of memory utilization
# TYPE mssql_memory_utilization_percentage gauge
mssql_memory_utilization_percentage 100

# HELP mssql_total_physical_memory_kb Total physical memory in KB
# TYPE mssql_total_physical_memory_kb gauge
mssql_total_physical_memory_kb 2096752

# HELP mssql_available_physical_memory_kb Available physical memory in KB
# TYPE mssql_available_physical_memory_kb gauge
mssql_available_physical_memory_kb 363284

# HELP mssql_total_page_file_kb Total page file in KB
# TYPE mssql_total_page_file_kb gauge
mssql_total_page_file_kb 2621040

# HELP mssql_available_page_file_kb Available page file in KB
# TYPE mssql_available_page_file_kb gauge
mssql_available_page_file_kb 620376
```

**Comment by tmatias** [comment]
A sample with the metrics I'm adding:

```
# HELP up UP Status
# TYPE up gauge
up 1

# HELP mssql_instance_local_time Number of seconds since epoch on local instance
# TYPE mssql_instance_local_time gauge
mssql_instance_local_time 1531331946

# HELP mssql_connections Number of active connections
# TYPE mssql_connections gauge
mssql_connections{database="master",state="current"} 57
mssql_connections{database="msdb",state="current"} 3

# HELP mssql_deadlocks Number of lock requests per second that resulted in a deadlock since last restart
# TYPE mssql_deadlocks gauge
mssql_deadlocks 0

# HELP mssql_user_errors Number of user errors/sec since last restart
# TYPE mssql_user_errors gauge
mssql_user_errors 183

# HELP mssql_sql_compilations Number of SQL compilations per second. Indicates the number of times the compile code path is entered. Includes compiles caused by statement-level recompilations in SQL Server. After SQL Server user activity is stable, this value reaches a steady state
# TYPE mssql_sql_compilations gauge
mssql_sql_compilations 29586

# HELP mssql_sql_recompilations Number of statement recompiles per second. Counts the number of times statement recompiles are triggered. Generally, you want the recompiles to be low
# TYPE mssql_sql_recompilations gauge
mssql_sql_recompilations 283

# HELP mssql_buffer_cache_hit_ratio Indicates the percentage of pages found in the buffer cache without having to read from disk. The ratio is the total number of cache hits divided by the total number of cache lookups over the last few thousand page accesses. After a long period of time, the ratio moves very little
# TYPE mssql_buffer_cache_hit_ratio gauge
mssql_buffer_cache_hit_ratio 4

# HELP mssql_checkpoint_pages Indicates the number of pages flushed to disk per second by a checkpoint or other operation that require all dirty pages to be flushed
# TYPE mssql_checkpoint_pages gauge
mssql_checkpoint_pages 1064

# HELP mssql_lock_waits Number of lock requests per second that required the caller to wait
# TYPE mssql_lock_waits gauge
mssql_lock_waits 21

# HELP mssql_page_splits Number of page splits per second that occur as the result of overflowing index pages
# TYPE mssql_page_splits gauge
mssql_page_splits 1148

# HELP mssql_kill_connection_errors Number of kill connection errors/sec since last restart
# TYPE mssql_kill_connection_errors gauge
mssql_kill_connection_errors 0

# HELP mssql_log_growths Total number of times the transaction log for the database has been expanded last restart
# TYPE mssql_log_growths gauge
mssql_log_growths{database="app"} 0
mssql_log_growths{database="tempdb"} 0
mssql_log_growths{database="model"} 0
mssql_log_growths{database="rdsadmin"} 1
mssql_log_growths{database="msdb"} 0
mssql_log_growths{database="mssqlsystemresource"} 0
mssql_log_growths{database="master"} 0

# HELP mssql_page_life_expectancy Indicates the minimum number of seconds a page will stay in the buffer pool on this node without references. The traditional advice from Microsoft used to be that the PLE should remain above 300 seconds
# TYPE mssql_page_life_expectancy gauge
mssql_page_life_expectancy 178103

# HELP mssql_io_stall Wait time (ms) of stall since last restart
# TYPE mssql_io_stall gauge
mssql_io_stall{database="master",type="read"} 383
mssql_io_stall{database="master",type="write"} 3715
mssql_io_stall{database="master",type="queued_read"} 0
mssql_io_stall{database="master",type="queued_write"} 0
mssql_io_stall{database="tempdb",type="read"} 62
mssql_io_stall{database="tempdb",type="write"} 143
mssql_io_stall{database="tempdb",type="queued_read"} 0
mssql_io_stall{database="tempdb",type="queued_write"} 0
mssql_io_stall{database="model",type="read"} 406
mssql_io_stall{database="model",type="write"} 2585
mssql_io_stall{database="model",type="queued_read"} 0
mssql_io_stall{database="model",type="queued_write"} 0
mssql_io_stall{database="msdb",type="read"} 1451
mssql_io_stall{database="msdb",type="write"} 6582
mssql_io_stall{database="msdb",type="queued_read"} 0
mssql_io_stall{database="msdb",type="queued_write"} 0
mssql_io_stall{database="rdsadmin",type="read"} 1163
mssql_io_stall{database="rdsadmin",type="write"} 26542
mssql_io_stall{database="rdsadmin",type="queued_read"} 0
mssql_io_stall{database="rdsadmin",type="queued_write"} 0
mssql_io_stall{database="app",type="read"} 2287
mssql_io_stall{database="app",type="write"} 2866
mssql_io_stall{database="app",type="queued_read"} 0
mssql_io_stall{database="app",type="queued_write"} 0
mssql_io_stall{database="app",type="read"} 479
mssql_io_stall{database="app",type="write"} 2163

# HELP mssql_io_stall_total Wait time (ms) of stall since last restart
# TYPE mssql_io_stall_total gauge
mssql_io_stall_total{database="master"} 3720
mssql_io_stall_total{database="tempdb"} 148
mssql_io_stall_total{database="model"} 2991
mssql_io_stall_total{database="msdb"} 7260
mssql_io_stall_total{database="rdsadmin"} 27705
mssql_io_stall_total{database="app"} 3243

# HELP mssql_batch_requests Number of Transact-SQL command batches received per second. This statistic is affected by all constraints (such as I/O, number of users, cachesize, complexity of requests, and so on). High batch requests mean good throughput
# TYPE mssql_batch_requests gauge
mssql_batch_requests 144190

# HELP mssql_page_fault_count Number of page faults since last restart
# TYPE mssql_page_fault_count gauge
mssql_page_fault_count 1429899

# HELP mssql_memory_utilization_percentage Percentage of memory utilization
# TYPE mssql_memory_utilization_percentage gauge
mssql_memory_utilization_percentage 100

# HELP mssql_total_physical_memory_kb Total physical memory in KB
# TYPE mssql_total_physical_memory_kb gauge
mssql_total_physical_memory_kb 2096752

# HELP mssql_available_physical_memory_kb Available physical memory in KB
# TYPE mssql_available_physical_memory_kb gauge
mssql_available_physical_memory_kb 363284

# HELP mssql_total_page_file_kb Total page file in KB
# TYPE mssql_total_page_file_kb gauge
mssql_total_page_file_kb 2621040

# HELP mssql_available_page_file_kb Available page file in KB
# TYPE mssql_available_page_file_kb gauge
mssql_available_page_file_kb 620376
```

**Comment by marcosfreccia** [comment]
Could we get more attraction to get this merged? I would like to add more metrics and test those ones.

**Pull request closed without merging**
